'use client';

/**
 * The whole brand, in one archive.
 *
 * Everything here is already served from this origin, so the kit is assembled
 * by fetching the same files the site itself uses — there is no second copy of
 * the brand to drift out of date. The font list is read from the manifest
 * rather than hardcoded, so a re-fetch of the faces is picked up automatically.
 */

import { PALETTE, SURFACES, SURFACE_ART, MARKS, TEXTURES, AUTOMATION_ICONS } from '@/lib/tokens';
import { ratio, levelFor } from '@/lib/contrast';

export type KitProgress = { done: number; total: number; label: string };

type Entry = { path: string; as: string };

const FAVICONS = [
  'favicon.svg', 'favicon-32.png', 'favicon-96.png', 'apple-touch-icon.png',
  'icon-192.png', 'icon-512.png', 'icon-maskable-512.png', 'site.webmanifest',
];

const OG = ['og-default.png', 'og-playbook.png', 'og-editor.png'];

/** The files that make up the kit, before the fonts are appended. */
function baseEntries(): Entry[] {
  return [
    ...Object.values(MARKS).map((p) => ({ path: p, as: `logo/${p.split('/').pop()}` })),
    ...FAVICONS.map((f) => ({ path: `/brand/favicon/${f}`, as: `favicon/${f}` })),
    ...OG.map((f) => ({ path: `/brand/og/${f}`, as: `open-graph/${f}` })),
    ...AUTOMATION_ICONS.map((n) => ({ path: `/brand/icons/${n}.svg`, as: `icons/${n}.svg` })),
    ...Object.values(TEXTURES).map((p) => ({ path: p, as: `textures/${p.split('/').pop()}` })),
    { path: '/brand/ASSETS.md', as: 'ASSETS.md' },
  ];
}

/** Machine-readable palette, so a kit can be wired into another toolchain. */
function paletteJson(): string {
  return JSON.stringify(
    {
      note: 'Generated by the Floatline design system. Values mirror src/styles/tokens.css.',
      palette: PALETTE.map((c) => ({ name: c.name, hex: c.hex, token: c.token, use: c.use })),
      surfaces: SURFACES.map((s) => {
        const art = SURFACE_ART[s.id];
        const contrast = (['fg', 'fg2', 'muted', 'signalText'] as const).map((k) => {
          const r = ratio(art[k], art.bg);
          return { role: k, hex: art[k], ratio: r ? Number(r.toFixed(2)) : null, level: r ? levelFor(r) : null };
        });
        return { id: s.id, label: s.label, hint: s.hint, ...art, contrast };
      }),
    },
    null,
    2
  );
}

export async function buildBrandKit(onProgress?: (p: KitProgress) => void): Promise<Blob> {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();

  const entries = baseEntries();

  // The fonts come from the manifest so the kit cannot list a face that is not
  // on disk, or miss one that is.
  let fontNote = '';
  try {
    const manifest = await (await fetch('/brand/fonts/fonts.manifest.json')).json();
    entries.push({ path: '/brand/fonts/fonts.manifest.json', as: 'fonts/fonts.manifest.json' });
    for (const f of manifest.fonts as { file: string }[]) {
      entries.push({ path: `/brand/fonts/${f.file}`, as: `fonts/${f.file}` });
    }
    fontNote = `${manifest.fonts.length} faces · ${manifest.licence}`;
  } catch {
    fontNote = 'fonts unavailable — the manifest could not be read';
  }

  entries.push({ path: '/_floatline/tokens.css', as: 'tokens.css' });

  const total = entries.length + 2;
  let done = 0;

  for (const e of entries) {
    onProgress?.({ done, total, label: e.as });
    if (e.path === '/_floatline/tokens.css') {
      // Not a served file: recovered from the live stylesheet instead, so the
      // kit ships the tokens the page is actually using.
      zip.file(e.as, tokensCss());
    } else {
      try {
        const res = await fetch(e.path);
        if (!res.ok) throw new Error(String(res.status));
        zip.file(e.as, await res.blob());
      } catch {
        // One missing asset must not lose the rest of the kit.
        zip.file(`_missing/${e.as}.txt`, `${e.path} could not be fetched\n`);
      }
    }
    done++;
  }

  onProgress?.({ done, total, label: 'palette.json' });
  zip.file('palette.json', paletteJson());
  done++;

  onProgress?.({ done, total, label: 'README.txt' });
  zip.file('README.txt', readme(fontNote));

  return zip.generateAsync({ type: 'blob', compression: 'STORE' });
}

/** Serialise the :root custom properties straight out of the live document. */
function tokensCss(): string {
  const out: string[] = [
    '/* Floatline design tokens, read out of the live stylesheet.',
    '   Generated by the brand kit download — the canonical source is',
    '   src/styles/tokens.css in the design system. */',
    '',
    ':root {',
  ];
  const seen = new Set<string>();
  for (const sheet of Array.from(document.styleSheets)) {
    let rules: CSSRuleList;
    try {
      rules = sheet.cssRules;
    } catch {
      continue; // cross-origin sheet; there are none, but do not assume
    }
    for (const rule of Array.from(rules)) {
      if (!(rule instanceof CSSStyleRule) || rule.selectorText !== ':root') continue;
      for (const prop of Array.from(rule.style)) {
        if (!prop.startsWith('--') || seen.has(prop)) continue;
        seen.add(prop);
        out.push(`  ${prop}: ${rule.style.getPropertyValue(prop).trim()};`);
      }
    }
  }
  out.push('}', '');
  return out.join('\n');
}

function readme(fontNote: string): string {
  return [
    'Floatline brand kit',
    '===================',
    '',
    'logo/        Six lockups — mark, wordmark light and dark, stacked, mono, outline.',
    'favicon/     Favicon, app icons and the web manifest.',
    'open-graph/  1200x630 share cards.',
    'icons/       The ten in-house automation glyphs. Stroked with currentColor,',
    '             so load them as a CSS mask if you want them to take a colour.',
    'textures/    Receipt-paper pattern and fine grain.',
    `fonts/       ${fontNote}`,
    'tokens.css   Every design token, as CSS custom properties.',
    'palette.json Machine-readable palette and surfaces, with measured WCAG ratios.',
    'ASSETS.md    What every file is and where it is used.',
    '',
    'Clear space is 0.5x the mark height on every side. Minimum mark 20px;',
    'below 120px wide, drop the wordmark and use the mark alone.',
    '',
    'Never invent a gradient. Floatline is a flat-colour brand on warm paper.',
    '',
  ].join('\n');
}
