/**
 * One-time font acquisition. Run with `npm run fonts:fetch`.
 *
 * Floatline's exports embed their own type. `getFontEmbedCSS` (html-to-image)
 * walks `document.styleSheets[].cssRules`, and a CROSS-ORIGIN sheet throws
 * SecurityError there — which html-to-image swallows. The failure mode is not
 * an error, it is every exported PNG silently rendering in fallback type. So
 * the faces must be same-origin, which means committed to `public/brand/fonts`.
 *
 * Google serves variable WOFF2 only to a modern browser UA; with the default
 * Node UA you get static TTF instead. Hence the explicit UA below.
 */
import { mkdir, writeFile, readdir, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'public/brand/fonts');

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

/**
 * Families, requested as AXIS RANGES rather than pinned weights.
 *
 * `wght@400;700` makes Google serve two separate static instances; `wght@200..800`
 * makes it serve the real variable font and declare `font-weight: 200 800` in the
 * @font-face. That declared range is the server telling us what it sent, so it is
 * what `variable: true` is checked against below — a far more honest signal than
 * sniffing bytes out of a compressed WOFF2.
 *
 * `opsz` never appears in Google's CSS (optical sizing is applied by the browser
 * via `font-optical-sizing: auto`), so it cannot be asserted here; requesting the
 * `opsz,wght` tuple is what makes the served file carry the axis.
 */
const FAMILIES = [
  {
    id: 'bricolage-grotesque',
    css: 'Bricolage+Grotesque:opsz,wght@12..96,200..800',
    family: 'Bricolage Grotesque',
    variable: true,
  },
  {
    id: 'manrope',
    css: 'Manrope:wght@200..800',
    family: 'Manrope',
    variable: true,
  },
  {
    id: 'ibm-plex-mono',
    css: 'IBM+Plex+Mono:wght@400;500;600',
    family: 'IBM Plex Mono',
    variable: false,
  },
];

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

/** WOFF2 magic — proves we got a compressed web font, not a TTF fallback. */
function assertWoff2(buf, file) {
  if (buf.subarray(0, 4).toString('latin1') !== 'wOF2') {
    throw new Error(`${file} is not a WOFF2 file — check the User-Agent.`);
  }
}

async function main() {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  const manifest = {
    note: 'Generated by scripts/fetch-fonts.mjs. Do not hand-edit.',
    userAgent: UA,
    licence: 'SIL Open Font License 1.1 — Bricolage Grotesque, Manrope, IBM Plex Mono',
    generatedFrom: [],
    fonts: [],
  };

  let n = 0;
  const cssBlocks = [];

  for (const fam of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
    manifest.generatedFrom.push(url);
    const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();
    if (!css.includes('@font-face')) throw new Error(`no @font-face returned for ${fam.family}`);

    const faces = [...css.matchAll(/@font-face\s*{([^}]+)}/g)].map((m) => m[1]);
    for (const face of faces) {
      const src = /src:\s*url\(([^)]+)\)/.exec(face);
      if (!src) continue;
      const href = src[1].replace(/['"]/g, '');
      if (!href.endsWith('.woff2')) throw new Error(`expected woff2, got ${href}`);

      const pick = (k) => (new RegExp(`${k}:\\s*([^;]+);`).exec(face) || [, ''])[1].trim();
      const style = pick('font-style') || 'normal';
      const weight = pick('font-weight') || '400';
      const unicodeRange = pick('unicode-range');

      const buf = Buffer.from(await (await fetch(href)).arrayBuffer());
      const file = `${fam.id}-${style}-${weight.replace(/\s+/g, '_')}-${n++}.woff2`;
      await writeFile(path.join(OUT, file), buf);

      assertWoff2(buf, file);
      if (fam.variable && !/^\d+\s+\d+$/.test(weight)) {
        throw new Error(
          `${fam.family} came back pinned at font-weight: ${weight}, not a range. ` +
            `Google served a static instance — request an axis range (wght@200..800).`
        );
      }

      manifest.fonts.push({
        family: fam.family,
        id: fam.id,
        style,
        weight,
        unicodeRange,
        file,
        bytes: buf.length,
        sha256: sha256(buf),
        variable: fam.variable,
      });
      cssBlocks.push({ family: fam.family, style, weight, file, unicodeRange });
    }
  }

  await writeFile(
    path.join(OUT, 'fonts.manifest.json'),
    JSON.stringify(manifest, null, 2) + '\n'
  );

  const files = (await readdir(OUT)).filter((f) => f.endsWith('.woff2'));
  console.log(`fetched ${files.length} woff2 files across ${FAMILIES.length} families`);
  console.log('now run: npm run fonts:css');
}

main().catch((e) => {
  console.error(`[fetch-fonts] ${e.message}`);
  process.exit(1);
});
